services:
  portfolio:
    image: nginx:alpine
    container_name: portfolio_romain
    restart: always
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`romain-gore.fr`) || Host(`www.romain-gore.fr`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls=true"
      - "traefik.http.routers.portfolio.tls.certresolver=ovhcloud"
    networks:
      - web

networks:
  web:
    external: true
